version: '3.2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name:  nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    networks:
     - nginx
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
     - nginx
    volumes:
     - ./nginx/certs:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - vhost:/etc/nginx/vhost.d
     - html:/usr/share/nginx/html
     - conf:/etc/nginx/conf.d

  jenkins:
    image: danghung/jenkins
    container_name: jenkins
    networks:
     - nginx
    volumes:
     - ./jenkins/jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
     - LETSENCRYPT_HOST=${JENKINS_LETSENCRYPT_HOST}
     - VIRTUAL_HOST=${JENKINS_VIRTUAL_HOST}
     - VIRTUAL_PORT=8080

volumes:
  vhost:
  html:
  conf:
networks:
  nginx:
    driver: bridge