version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name:  nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    networks:
     - elk
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /etc/nginx/conf.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy


 
  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  fluentd:
    build:
      context: fluentd/
    links:
      - "elasticsearch"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880"
    networks:
      - elk
    depends_on:
      - elasticsearch
    expose:
      - "9880"

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    environment:
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
     - LETSENCRYPT_HOST=${KIBANA_LETSENCRYPT_HOST}
     - VIRTUAL_HOST=${KIBANA_VIRTUAL_HOST}
     - VIRTUAL_PORT=5601
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    expose:
      - "5601"

  curator:
    build:
      context: curator/
    environment:
     - UNIT_COUNT=${LOGS_KEEP_DAYS}
     - UNIT=days
     - ES_HOST=elasticsearch
    networks:
      - elk
    depends_on:
      - elasticsearch


networks:
  elk:
    driver: bridge
