version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - nginx

  elasticsearch2:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticdata2:/usr/share/elasticsearch/data

    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
 #     - node.name=es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - nginx

  elasticsearch3:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticdata3:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
  #    - node.name=es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    networks:
      - nginx

  fluentd:
    build:
      context: fluentd/
    links:
      - "elasticsearch"
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "9880:9880"
    networks:
      - nginx
    depends_on:
      - elasticsearch
    expose:
      - "9880"
  # logstash:
  #   build:
  #     context: logstash/
  #   volumes:
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
  #     - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
  #   ports:
  #     - "21201:21201"
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   networks:
  #     - nginx
  #   depends_on:
  #     - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - nginx
    environment:
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
     - LETSENCRYPT_HOST=${KIBANA_LETSENCRYPT_HOST}
     - VIRTUAL_HOST=${KIBANA_VIRTUAL_HOST}
     - VIRTUAL_PORT=5601
    depends_on:
      - elasticsearch
    expose:
      - "5601"

  curator:
    build:
      context: curator/
    environment:
     - UNIT_COUNT=${LOGS_KEEP_DAYS}
     - UNIT=days
     - ES_HOST=elasticsearch
    networks:
      - nginx
    depends_on:
      - elasticsearch


networks:
  nginx:
    external: true