version: '3'

services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
     - "80:80"
     - "443:443"
    networks:
     - elk
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    networks:
     - elk
    volumes:
     - ./nginx/certs:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - ./nginx/vhost.d:/etc/nginx/vhost.d
     - ./nginx/html:/usr/share/nginx/html
     - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
     - nginx-proxy

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    environment:
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
     - LETSENCRYPT_HOST=${KIBANA_LETSENCRYPT_HOST}
     - VIRTUAL_HOST=${KIBANA_VIRTUAL_HOST}
     - VIRTUAL_PORT=5601
    depends_on:
      - elasticsearch

  jenkins:
    image: danghung/jenkins
    container_name: jenkins
    networks:
     - elk
    volumes:
     - ./jenkins/jenkins_home:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
     - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
     - LETSENCRYPT_HOST=${JENKINS_LETSENCRYPT_HOST}
     - VIRTUAL_HOST=${JENKINS_VIRTUAL_HOST}
     - VIRTUAL_PORT=8080

networks:

  elk:
    driver: bridge
